// Generated by CoffeeScript 1.6.3
(function() {
  var ImageLayer, Layer, TranslationLayer, TranslationRightLayer, easeOutQuart, easing, layers, mouseX, pageWidth, parallaxWidth, pendingAnimFrame, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Layer = (function() {
    function Layer(element, options) {
      this.$el = $(element);
      this.el = this.$el[0];
      this.offset = this.x = options.x;
      this.origin = {
        x: this.x
      };
      this.k = options.k;
      this.initialize();
    }

    Layer.prototype.update = function(p) {
      var x;
      x = this.k * p + this.origin.x;
      if (Math.abs(x - this.x) >= 0) {
        this.x = x;
        return this.transform();
      }
    };

    Layer.prototype.initialize = function() {};

    Layer.prototype.transform = function() {};

    return Layer;

  })();

  TranslationLayer = (function(_super) {
    __extends(TranslationLayer, _super);

    function TranslationLayer() {
      _ref = TranslationLayer.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TranslationLayer.prototype.initialize = function() {
      return this.el.style.left = "" + this.offset + "px";
    };

    TranslationLayer.prototype.transform = function() {
      return this.$el.css({
        'transform': "translate(" + (this.offset - this.x) + "px, 0)"
      });
    };

    return TranslationLayer;

  })(Layer);

  ImageLayer = (function(_super) {
    __extends(ImageLayer, _super);

    function ImageLayer() {
      _ref1 = ImageLayer.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    ImageLayer.prototype.initialize = function() {
      this.$el.css({
        'background-size': "" + (this.$el.outerWidth() + this.k * 2.0) + "px auto"
      });
      return this.transform();
    };

    ImageLayer.prototype.transform = function() {
      return this.el.style.backgroundPosition = "" + (-this.x) + "px top";
    };

    return ImageLayer;

  })(Layer);

  TranslationRightLayer = (function(_super) {
    __extends(TranslationRightLayer, _super);

    function TranslationRightLayer() {
      _ref2 = TranslationRightLayer.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    TranslationRightLayer.prototype.initialize = function() {
      this.offset = this.x;
      return this.el.style.left = "" + this.offset + "px";
    };

    TranslationRightLayer.prototype.transform = function() {
      return this.$el.css({
        'transform': "translate(" + (this.offset - this.x) + "px, 0)"
      });
    };

    return TranslationRightLayer;

  })(Layer);

  pageWidth = $('body').outerWidth();

  parallaxWidth = pageWidth * 0.6;

  layers = [
    new ImageLayer('.background', {
      x: 30.0,
      k: 30.0
    }), new TranslationLayer('.content', {
      x: 0.0,
      k: 40.0
    }), new TranslationLayer('.contact', {
      x: -200.0,
      k: 200.0
    }), new TranslationRightLayer('.projects', {
      x: pageWidth,
      k: 200.0
    })
  ];

  pendingAnimFrame = false;

  mouseX = void 0;

  easeOutQuart = function(d) {
    return function(t) {
      return -(Math.pow(t / d - 1, 4) - 1);
    };
  };

  easing = easeOutQuart(1.8);

  $(document).on('mousemove', function(event) {
    if (mouseX === void 0) {
      mouseX = mouseX;
    }
    mouseX = event.pageX;
    if (pendingAnimFrame) {
      return;
    }
    pendingAnimFrame = true;
    return window.requestAnimationFrame(function() {
      var layer, p, pEased, _i, _len, _results;
      pendingAnimFrame = false;
      p = Math.min(+1.0, Math.max(-1.0, (mouseX - pageWidth / 2) / parallaxWidth * 2));
      pEased = (p / Math.abs(p)) * easing(Math.abs(p));
      _results = [];
      for (_i = 0, _len = layers.length; _i < _len; _i++) {
        layer = layers[_i];
        _results.push(layer.update(pEased));
      }
      return _results;
    });
  });

}).call(this);
