// Generated by CoffeeScript 1.7.1
(function() {
  var REQUEST_ANIM, easeOutQuart, easing, pageWidth, parallaxWidth, step;

  pageWidth = $('body').outerWidth();

  parallaxWidth = pageWidth * 0.6;

  easeOutQuart = function(d) {
    return function(t) {
      return -(Math.pow(t / d - 1, 4) - 1);
    };
  };

  easing = easeOutQuart(1.8);

  window.mouseX = 0;

  window.container = null;

  $(document).ready(function() {
    $(document).on('mousemove', function(event) {
      window.mouseX = event.pageX;
      if (!REQUEST_ANIM) {
        return step();
      }
    });
    return window.container = $('body');
  });

  REQUEST_ANIM = false;

  step = function() {
    var origin, p;
    if (REQUEST_ANIM) {
      window.requestAnimationFrame(step);
    }
    p = Math.min(+1.0, Math.max(0, (window.mouseX - pageWidth / 3) / parallaxWidth * 2));
    origin = p * 100 + '% 50%';
    console.log(origin);
    if (window.container) {
      return window.container.css('perspective-origin', origin);
    }
  };

  if (REQUEST_ANIM) {
    window.requestAnimationFrame(step);
  }

}).call(this);

//# sourceMappingURL=script.map
